name: Nightly test at main branch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-5'

jobs:
  setup:
    name: Setup variables
    runs-on: 'ubuntu-24.04'
    outputs:
      min_python: ${{ steps.vars.outputs.min_python }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Python version for other CI jobs
        id: vars
        run: echo "min_python=$(< .github/workflows/python-version-ci)" >> "$GITHUB_OUTPUT"

  tests:
    name: Tests
    needs: setup
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        python:
          - version: '${{needs.setup.outputs.min_python}}'
            tox-env: 'nightly'
    uses: ./.github/workflows/test.yml
    with:
      os-variant: ${{ matrix.os }}
      python-version: ${{ matrix.python.version }}
      tox-env: ${{ matrix.python.tox-env }}
    secrets: inherit

  tests-at-lower-bound:
    name: Tests at lower bound
    needs: setup
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        python:
          - version: '${{needs.setup.outputs.min_python}}'
    runs-on: ${{ matrix.os }}
    env:
        ESS_PROTECTED_FILESTORE_USERNAME: ${{ secrets.ESS_PROTECTED_FILESTORE_USERNAME }}
        ESS_PROTECTED_FILESTORE_PASSWORD: ${{ secrets.ESS_PROTECTED_FILESTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python.version }}
      - run: uv run --extra=test --resolution=lowest-direct pytest
