import re
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    "--nightly",
    default="",
    help="List of dependencies to install from main branch for nightly tests, "
    "separated by commas.",
)
args = parser.parse_args()

header = "# Generated by 'tox -e deps', DO NOT EDIT MANUALLY!'\n"

dependencies = []

with open("../pyproject.toml", "r") as toml_file:
    toml_contents = toml_file.read()
    match = re.search(r"dependencies = \[(.*?)\]", toml_contents, re.DOTALL)
    if not match:
        raise RuntimeError("Failed to parse pyproject.toml")
    for dependency in match.group(1).split(",\n"):
        dependency = dependency.strip().strip('"')
        if dependency:
            dependencies.append(dependency)

with open("base.in", "w") as f:
    f.write(header)
    f.write("\n".join(dependencies))

nightly = args.nightly.split(",")
dependencies = [dep for dep in dependencies if not dep.startswith(tuple(nightly))]
dependencies += [f"{arg} @ git+https://github.com/scipp/{arg}@main" for arg in nightly]

with open("nightly.in", "w") as f:
    f.write(header)
    f.write("\n".join(dependencies))
